Traceback (most recent call last):
  File "C:\Users\alimo\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\alimo\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\alimo\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\alimo\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\alimo\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\alimo\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\alimo\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\alimo\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from myst_nb import glue
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.cm as cm

x=np.linspace(-2, 2, 10) #x coordinates arranged on [-2,2]
y=np.linspace(-2, 2, 10) #y coordinates arranged on [-2,2]

X,Y = np.meshgrid(x, y) #make the plot grid
(U,V)=(2*Y,2*X)        #define the vector field values at each point

fig,ax=plt.subplots(figsize=(5,5))
ax.axis([-2,2,-2,2])
ax.xaxis.set_ticks([])
ax.yaxis.set_ticks([])
#----------------------------------
start=[ #start points of selected field lines
    [-2,-2],[-2,2],[2,-2],[2,2],
    [-1.9,2],[-1.6,2],[-1.1,2],
    [-1.9,-2],[-1.6,-2],[-1.1,-2],
    [-2,-1.9],[-2,-1.6],[-2,-1.1],
    [2,-1.9],[2,-1.6],[2,-1.1]
    ]
#----------------------------------

ax.streamplot(X,Y,U,V,start_points=start,density=10) # stream plot
glue("saddle_fig", fig, display=False)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
[1;32m~\anaconda3\lib\site-packages\PIL\ImageFile.py[0m in [0;36m_save[1;34m(im, fp, tile, bufsize)[0m
[0;32m    503[0m     [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 504[1;33m         [0mfh[0m [1;33m=[0m [0mfp[0m[1;33m.[0m[0mfileno[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    505[0m         [0mfp[0m[1;33m.[0m[0mflush[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mAttributeError[0m: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

[1;31mSystemError[0m                               Traceback (most recent call last)
[1;32m~\anaconda3\lib\site-packages\IPython\core\formatters.py[0m in [0;36m__call__[1;34m(self, obj)[0m
[0;32m    339[0m                 [1;32mpass[0m[1;33m[0m[1;33m[0m[0m
[0;32m    340[0m             [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 341[1;33m                 [1;32mreturn[0m [0mprinter[0m[1;33m([0m[0mobj[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    342[0m             [1;31m# Finally look for special method names[0m[1;33m[0m[1;33m[0m[0m
[0;32m    343[0m             [0mmethod[0m [1;33m=[0m [0mget_real_method[0m[1;33m([0m[0mobj[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mprint_method[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\IPython\core\pylabtools.py[0m in [0;36mprint_figure[1;34m(fig, fmt, bbox_inches, base64, **kwargs)[0m
[0;32m    149[0m         [0mFigureCanvasBase[0m[1;33m([0m[0mfig[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    150[0m [1;33m[0m[0m
[1;32m--> 151[1;33m     [0mfig[0m[1;33m.[0m[0mcanvas[0m[1;33m.[0m[0mprint_figure[0m[1;33m([0m[0mbytes_io[0m[1;33m,[0m [1;33m**[0m[0mkw[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    152[0m     [0mdata[0m [1;33m=[0m [0mbytes_io[0m[1;33m.[0m[0mgetvalue[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    153[0m     [1;32mif[0m [0mfmt[0m [1;33m==[0m [1;34m'svg'[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\backend_bases.py[0m in [0;36mprint_figure[1;34m(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)[0m
[0;32m   2253[0m                 [1;31m# force the figure dpi to 72), so we need to set it again here.[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2254[0m                 [1;32mwith[0m [0mcbook[0m[1;33m.[0m[0m_setattr_cm[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mfigure[0m[1;33m,[0m [0mdpi[0m[1;33m=[0m[0mdpi[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2255[1;33m                     result = print_method(
[0m[0;32m   2256[0m                         [0mfilename[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2257[0m                         [0mfacecolor[0m[1;33m=[0m[0mfacecolor[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\backend_bases.py[0m in [0;36mwrapper[1;34m(*args, **kwargs)[0m
[0;32m   1667[0m             [0mkwargs[0m[1;33m.[0m[0mpop[0m[1;33m([0m[0marg[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1668[0m [1;33m[0m[0m
[1;32m-> 1669[1;33m         [1;32mreturn[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1670[0m [1;33m[0m[0m
[0;32m   1671[0m     [1;32mreturn[0m [0mwrapper[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py[0m in [0;36mprint_png[1;34m(self, filename_or_obj, metadata, pil_kwargs, *args)[0m
[0;32m    507[0m         """
[0;32m    508[0m         [0mFigureCanvasAgg[0m[1;33m.[0m[0mdraw[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 509[1;33m         mpl.image.imsave(
[0m[0;32m    510[0m             [0mfilename_or_obj[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mbuffer_rgba[0m[1;33m([0m[1;33m)[0m[1;33m,[0m [0mformat[0m[1;33m=[0m[1;34m"png"[0m[1;33m,[0m [0morigin[0m[1;33m=[0m[1;34m"upper"[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    511[0m             dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)

[1;32m~\anaconda3\lib\site-packages\matplotlib\image.py[0m in [0;36mimsave[1;34m(fname, arr, vmin, vmax, cmap, format, origin, dpi, metadata, pil_kwargs)[0m
[0;32m   1614[0m         [0mpil_kwargs[0m[1;33m.[0m[0msetdefault[0m[1;33m([0m[1;34m"format"[0m[1;33m,[0m [0mformat[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1615[0m         [0mpil_kwargs[0m[1;33m.[0m[0msetdefault[0m[1;33m([0m[1;34m"dpi"[0m[1;33m,[0m [1;33m([0m[0mdpi[0m[1;33m,[0m [0mdpi[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1616[1;33m         [0mimage[0m[1;33m.[0m[0msave[0m[1;33m([0m[0mfname[0m[1;33m,[0m [1;33m**[0m[0mpil_kwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1617[0m [1;33m[0m[0m
[0;32m   1618[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\PIL\Image.py[0m in [0;36msave[1;34m(self, fp, format, **params)[0m
[0;32m   2238[0m [1;33m[0m[0m
[0;32m   2239[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2240[1;33m             [0msave_handler[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mfp[0m[1;33m,[0m [0mfilename[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   2241[0m         [1;32mfinally[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2242[0m             [1;31m# do what we can to clean up[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\PIL\PngImagePlugin.py[0m in [0;36m_save[1;34m(im, fp, filename, chunk, save_all)[0m
[0;32m   1346[0m         [0m_write_multiple_frames[0m[1;33m([0m[0mim[0m[1;33m,[0m [0mfp[0m[1;33m,[0m [0mchunk[0m[1;33m,[0m [0mrawmode[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1347[0m     [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1348[1;33m         [0mImageFile[0m[1;33m.[0m[0m_save[0m[1;33m([0m[0mim[0m[1;33m,[0m [0m_idat[0m[1;33m([0m[0mfp[0m[1;33m,[0m [0mchunk[0m[1;33m)[0m[1;33m,[0m [1;33m[[0m[1;33m([0m[1;34m"zip"[0m[1;33m,[0m [1;33m([0m[1;36m0[0m[1;33m,[0m [1;36m0[0m[1;33m)[0m [1;33m+[0m [0mim[0m[1;33m.[0m[0msize[0m[1;33m,[0m [1;36m0[0m[1;33m,[0m [0mrawmode[0m[1;33m)[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1349[0m [1;33m[0m[0m
[0;32m   1350[0m     [1;32mif[0m [0minfo[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\PIL\ImageFile.py[0m in [0;36m_save[1;34m(im, fp, tile, bufsize)[0m
[0;32m    510[0m             [1;32mif[0m [0mo[0m [1;33m>[0m [1;36m0[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    511[0m                 [0mfp[0m[1;33m.[0m[0mseek[0m[1;33m([0m[0mo[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 512[1;33m             [0me[0m[1;33m.[0m[0msetimage[0m[1;33m([0m[0mim[0m[1;33m.[0m[0mim[0m[1;33m,[0m [0mb[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    513[0m             [1;32mif[0m [0me[0m[1;33m.[0m[0mpushes_fd[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    514[0m                 [0me[0m[1;33m.[0m[0msetfd[0m[1;33m([0m[0mfp[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mSystemError[0m: tile cannot extend outside image
LinAlgError: Singular matrix

